apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: v0.35.0
  name: prometheus-operator
  namespace: openshift-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: prometheus-operator
        app.kubernetes.io/version: v0.35.0
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --logtostderr=true
        - --config-reloader-image=jimmidyson/configmap-reload:v0.3.0
        - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.35.0
        - --namespaces=openshift-monitoring
        image: quay.io/coreos/prometheus-operator:v0.35.0
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources: {}
        securityContext: {}
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext: {}
      serviceAccountName: prometheus-operator
